/**
 * This code was generated by Builder.io
 */
import React from "react";
import SearchResults from "./SearchResults.tsx";
import SidePanel from "./SidePanel.tsx";

const MainContent: React.FC = () => {
  return (
    <main className="self-center mt-11 ml-7 w-full max-w-[1292px] max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <SearchResults />
        <SidePanel />
      </div>
    </main>
  );
};

export default MainContent;
