/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TabItem {
  icon: string;
  label: string;
  alt: string;
}

const tabItems: TabItem[] = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b22aa989ad7e78c080340b82ce8c8542626446e5ba071d670a85914ecfc55efd?placeholderIfAbsent=true&apiKey=2ba0fb7325a84f4fa5c4b1eda3d92e31",
    label: "Web",
    alt: "Web Icon",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8a192c2558c69c6830adf4355c5204a6e4c30af936931c2bfa95be7dbeb5a348?placeholderIfAbsent=true&apiKey=2ba0fb7325a84f4fa5c4b1eda3d92e31",
    label: "Images",
    alt: "Images Icon",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6022ee6a9ce9e498593650e123b7d23d8aba0ea471c9f412a3d2fc1d31bf8d73?placeholderIfAbsent=true&apiKey=2ba0fb7325a84f4fa5c4b1eda3d92e31",
    label: "Videos",
    alt: "Videos Icon",
  },
];

const SearchTabs: React.FC = () => {
  return (
    <nav className="flex flex-wrap gap-5 justify-between items-start mt-11 ml-48 max-w-full text-2xl text-white whitespace-nowrap w-[527px] max-md:mt-10">
      {tabItems.map((item, index) => (
        <div key={index} className="flex gap-6">
          <img
            loading="lazy"
            src={item.icon}
            alt={item.alt}
            className="object-contain shrink-0 self-start w-7 aspect-square"
          />
          <div>{item.label}</div>
        </div>
      ))}
    </nav>
  );
};

export default SearchTabs;
