/**
 * This code was generated by Builder.io
 */
import React from "react";

interface LinkItem {
  icon: string;
  label: string;
  alt: string;
}

const linkItems: LinkItem[] = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/03ea8333c24c408a9f792a02df72fc728f779daf28eb0a68335fb96f782745fe?placeholderIfAbsent=true&apiKey=2ba0fb7325a84f4fa5c4b1eda3d92e31",
    label: "Official Page",
    alt: "Official Page Icon",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2b62e5184d972224b21ba4d98b91ea6f00af89cfe706674577128a98616da59e?placeholderIfAbsent=true&apiKey=2ba0fb7325a84f4fa5c4b1eda3d92e31",
    label: "Gitlab",
    alt: "Gitlab Icon",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/33034b66ceafcf84598a15f114a9f02ae12dd0eaddef327c106c36bfddae20e0?placeholderIfAbsent=true&apiKey=2ba0fb7325a84f4fa5c4b1eda3d92e31",
    label: "Wikipedia",
    alt: "Wikipedia Icon",
  },
];

const SidePanel: React.FC = () => {
  return (
    <aside className="flex flex-col ml-5 w-[37%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col items-start px-11 pt-8 pb-16 mx-auto w-full text-xl font-bold text-white bg-white bg-opacity-30 rounded-[30px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/430bc7971d713718b7de8afda14afb50d95cd3bdd8e3e5d4eaac2b4347ceb41d?placeholderIfAbsent=true&apiKey=2ba0fb7325a84f4fa5c4b1eda3d92e31"
          alt="SearX Logo"
          className="object-contain max-w-full aspect-[2.66] w-[370px]"
        />
        <p className="self-stretch mt-8 max-md:mr-1.5">
          Searx is a fredsdsde and open-source metasearch engine, available under the
          GNU Affero General Public License version 3, with the aim of
          protecting the privacy of its users. To this end, Searx does not share
          users' IP addresses or search history with the search engines from
          which it gathers results.
        </p>
        <p className="mt-6">
          Developer: <span className="">Adam Tauber</span>
        </p>
        <p className="self-stretch mt-4">
          <span className="text-white">Programming Languages:</span>{" "}
          <span className="text-white ">Python, Html, etc.</span>
        </p>
        <p className="mt-5">
          <span className="text-white">License:</span>
          <span className="text-white "> AGPL-3.0</span>
        </p>
        <div className="flex gap-10 mt-14 text-base max-md:mt-10">
          {linkItems.map((item, index) => (
            <div key={index} className="flex flex-col">
              <img
                loading="lazy"
                src={item.icon}
                alt={item.alt}
                className="object-contain self-center aspect-square w-[59px]"
              />
              <div className="mt-2.5">{item.label}</div>
            </div>
          ))}
        </div>
      </div>
    </aside>
  );
};

export default SidePanel;
